.gitignore
Classes/check.py
Classes/frozen.py
Functions/Winding/comp_wind_sym.py
Functions/Winding/reverse_wind_mat.py
Functions/Winding/shift_wind_mat.py

Fixed various typos in comments

---

Functions/FEMM/assign_FEMM_surface.py
Tests/Validation/Machine/IPMSM_xxx.py

Fixed conditionals where "lam" was used instead of "rotor".
Also corrected IPMSM unittest, which didn't show the error, since magnetization was "radial".

fixed wrong conditionals in assign_FEMM_surface

---

Methods/Simulation/MagFEMM/solve_FEMM.py

To utilize "new" FEMM feature to speed up calculation.

[NF] FEMM previous solution

---

Classes/InCurrentDQ.py
Functions/FEMM/create_FEMM_circuit_material.py
Generator/ClassesRef/Simulation/InCurrentDQ.csv
Methods/Simulation/InCurrentDQ/__init__.py
Methods/Simulation/InCurrentDQ/gen_input.py

This is a proposal of an InCurrentDQ class that can be used to input dq-reference frame stator currents instead of phase currents with InCurrent class.
I copied and adapted the InCurrent class code. I think this is the most straight forward solution.
An other solution could be to include an optional current transformation within InCurrent class.
What do you think?
Best regards,
Sebastian

[NF] InCurrentDQ

---

Generator/ClassGenerator/properties_generator.py
Generator/ClassGenerator/str_method_generator.py
Generator/read_fct.py
Tests/Classes/test_classes.py

[BC] Corrects bugs caused by the last PR

[BC] Correct tests bugs caused by class generator modifications

---

pyleecan/Functions/Plot/plot_A_2D.py
pyleecan/Functions/Plot/plot_A_3D.py
pyleecan/Functions/Plot/plot_A_4D.py
pyleecan/Functions/Plot/plot_A_cfft2.py
pyleecan/Functions/Plot/plot_A_fft2.py
pyleecan/Functions/Plot/plot_A_fft_space.py
pyleecan/Functions/Plot/plot_A_fft_time.py
pyleecan/Functions/Plot/plot_A_quiver_2D.py
pyleecan/Functions/Plot/plot_A_space.py
pyleecan/Functions/Plot/plot_A_surf.py
pyleecan/Functions/Plot/plot_A_time.py
pyleecan/Functions/Plot/plot_A_time_space.py
pyleecan/Methods/Output/Output/plot/plot_A_cfft2.py
pyleecan/Methods/Output/Output/plot/plot_A_fft2.py
pyleecan/Methods/Output/Output/plot/plot_A_fft_space.py
pyleecan/Methods/Output/Output/plot/plot_A_fft_time.py
pyleecan/Methods/Output/Output/plot/plot_A_space.py
pyleecan/Methods/Output/Output/plot/plot_A_surf.py
pyleecan/Methods/Output/Output/plot/plot_A_time.py

Automatically show figures if no 'fig' input parameter is provided. See #154 
In general there is some inconsistancy between the plot_A_xxx methods regarding 'fig' input parameter. So it's maybe worth to revise them.

[BC] show figure of plot_A_xxx methods

---

pyleecan/Functions/Optimization/update.py
pyleecan/Methods/Optimization/OptiGenAlgNsga2Deap/create_toolbox.py
pyleecan/Methods/Optimization/OptiGenAlgNsga2Deap/solve.py
pyleecan/Methods/Output/XOutput/plot_generation.py

[CO] removed limitation, that optimization simulation output could only be of type Output
[BC] adapted plot_generation to recent changes in output of Optimization

[BC][CO] Optimization

---

Tests/Plot/test_ICEM_2020.py
Tests/Validation/Optimization/test_Binh_and_Korn.py
Tests/Validation/Optimization/test_opti_datakeeper_list.py
Tests/Validation/Optimization/test_opti_preprocessing.py
Tests/Validation/Optimization/test_zdt3.py
Tests/Validation/Simulation/Multisimulation/test_slot_scale.py
pyleecan/Classes/DataKeeper.py
pyleecan/Classes/OptiConstraint.py
pyleecan/Classes/OptiDesignVar.py
pyleecan/Classes/OptiGenAlg.py
pyleecan/Classes/OptiProblem.py
pyleecan/Classes/PostFunction.py
pyleecan/Functions/Optimization/evaluate.py
pyleecan/Generator/ClassGenerator/properties_generator.py
pyleecan/Methods/Simulation/VarLoad/get_elec_datakeeper.py
pyleecan/Methods/Simulation/VarLoad/get_mag_datakeeper.py
pyleecan/Methods/Simulation/VarLoadCurrent/gen_datakeeper_list.py
pyleecan/Methods/Simulation/VarLoadCurrent/get_elec_datakeeper.py

This PR updates some lambda functions to lambda function strings (according to #172).
It also add the possibility to use np and random in the function string, e.g. `func_str = "lambda x, np=np: np.abs(x)"`
(This seems a little odd, but will work for now. Maybe someone has a better solution.)

[CC] lambda function strings

---

Tests/Methods/Machine/test_get_lam_list.py
pyleecan/Methods/Machine/Machine/get_lam_list.py
pytest.ini

+ additional marker DEV in pytest.ini for test on actual code changes, i.e. test marker should be remove from tests before commiting code

optional input to get_lam_list to return only rotor or stator laminations

---

Tests/Methods/Slot/test_SlotDC.py
Tests/Validation/Simulation/test_EM_FEMM_IPMSM_varload.py
pyleecan/Classes/Class_Dict.json
pyleecan/Classes/SlotDC.py
pyleecan/Functions/Simulation/VarSimu/run_single_simu.py
pyleecan/Generator/ClassesRef/Slot/SlotDC.csv
pyleecan/Methods/Machine/Machine/get_lam_list.py
pyleecan/Methods/Slot/SlotDC/__init__.py
pyleecan/Methods/Slot/SlotDC/_comp_point_coordinate.py
pyleecan/Methods/Slot/SlotDC/build_geometry.py
pyleecan/Methods/Slot/SlotDC/check.py
pyleecan/Methods/Slot/SlotDC/comp_angle_opening.py
pyleecan/Methods/Slot/SlotDC/comp_height.py
pyleecan/Methods/Slot/SlotDC/comp_height_wind.py
pyleecan/Methods/Slot/SlotDC/comp_surface.py
pyleecan/Methods/Slot/SlotDC/comp_surface_wind.py
pyleecan/Methods/Slot/SlotDC/get_surface_wind.py

Here is a Pull request to add a new slot cf issue #193

Slot dc webinar

---

Tests/Functions/test_gmsh2.py
pyleecan/Functions/GMSH/__init__.py
pyleecan/Functions/GMSH/draw_GMSH.py
pyleecan/Functions/GMSH/get_boundary_condition.py

This is work in progress to add boundary condition lines into Gmsh file aiming to be used for Elmer Coupling.

[WP] Added boundary condition lines to Gmsh file

---

Tests/Functions/test_gmsh2.py
Tests/Functions/test_magelmer.py
pyleecan/Functions/GMSH/__init__.py
pyleecan/Functions/GMSH/draw_GMSH.py
pyleecan/Functions/GMSH/get_air_box.py
pyleecan/Functions/GMSH/get_boundary_condition.py
pyleecan/Functions/GMSH/get_sliding_band.py
pyleecan/Methods/Machine/Shaft/build_geometry.py
pyleecan/Methods/Simulation/MagElmer/comp_flux_airgap.py
pyleecan/Methods/Simulation/MagElmer/gen_elmer_mesh.py
pyleecan/Methods/Simulation/MagElmer/get_path_save_fea.py
pyleecan/Methods/Simulation/MagElmer/solve_FEA.py

Hi,
This PR add some boundary conditions in Gmsh file and start populating the skeleton for Elmer Coupling. In this PR some code has been added to convert the Gmsh file into an Elmer mesh via ElmerGrid process call.
It is assumed that ElmerGrid is installed and in the PATH.

Gmsh file to Elmer Mesh conversion

---

Tests/Methods/Machine/test_Magnet_Type_15_meth.py
Tests/Validation/Simulation/test_FEMM_import_model.py
pyleecan/Classes/Class_Dict.json
pyleecan/Classes/MagnetType15.py
pyleecan/Classes/import_all.py
pyleecan/Functions/load_switch.py
pyleecan/Generator/ClassesRef/Machine/MagnetType15.csv
pyleecan/Methods/Machine/Frame/comp_mass.py
pyleecan/Methods/Machine/Frame/comp_volume.py
pyleecan/Methods/Machine/LamSlotMag/build_geometry.py
pyleecan/Methods/Machine/LamSlotWind/comp_lengths_winding.py
pyleecan/Methods/Machine/MagnetType15/build_geometry.py
pyleecan/Methods/Machine/MagnetType15/comp_angle_opening.py
pyleecan/Methods/Machine/MagnetType15/comp_height.py
pyleecan/Methods/Machine/Shaft/comp_mass.py
pyleecan/Methods/Machine/WindingUD/comp_connection_mat.py
pyleecan/Methods/Output/XOutput/plot_pareto.py

Hello Pierre,
although you are preparing the unified slots, I would like to add an other magnet type.
The implementation is not perfect, because the actual slot is not parallel. Nevertheless it may be useful to some.
BR, Sebastian

MagnetType15 - polar bottom, curved top, parallel sides

---

requirements.txt

There is a bug in numpy 1.19.4 -> Temporary downgrade requirement.

[BC] Update requirements.txt

---

pyleecan/Functions/Plot/plot_2D.py
pyleecan/Functions/Plot/plot_2D_Data.py
pyleecan/GUI/Dialog/DMachineSetup/SPreview/WMachineTable/Ui_WMachineTable.py
pyleecan/GUI/Dialog/DMachineSetup/SPreview/WMachineTable/WMachineTable.py
pyleecan/GUI/Dialog/DMachineSetup/SPreview/WMachineTable/WMachineTable.ui
pyleecan/Methods/Machine/LamSlotWind/plot_mmf_unit.py
pyleecan/Methods/Machine/Machine/plot.py

This PR also introduces the "win_title" argument for plot_2D_Data to change the title of the plot windows.

[CO] Improving SPreview plot

---

Tests/Functions/test_magelmer.py
Tests/Validation/Simulation/test_FEMM_periodicity.py
pyleecan/Classes/Class_Dict.json
pyleecan/Classes/RefTriangle3.py
pyleecan/GUI/Dialog/DMachineSetup/SPreview/WMachineTable/Ui_WMachineTable.py
pyleecan/GUI/Dialog/DMachineSetup/SPreview/WMachineTable/WMachineTable.ui
pyleecan/Generator/ClassesRef/Mesh/Interpolation/RefTriangle3.csv
pyleecan/Methods/Simulation/MagFEMM/comp_flux_airgap.py
pyleecan/Methods/Simulation/MagFEMM/solve_FEMM_parallel.py

This PR correct some bug currently on the master. 
In particular it is the follow up of #274 by solving the issue around FEMM parallelization and Handler (checked by temporally removing as_dict from FEMM_Handler, I kept this modification because it solve the save and copy in case of is_closefemm = False)

Miscellaneous Bug Correction 

---

pyleecan/Methods/Mesh/MeshMat/get_cell_area.py
pyleecan/Methods/Output/OutMag/get_demag.py

This PR should be merged after IronLoss PR to correct group name.

[CC] demagnetization

---

Tests/Plot/test_ICEM_2020.py
Tests/Validation/Simulation/Force/test_Benchmark_AGSF_Rag_variation.py
Tests/Validation/Simulation/Force/test_Benchmark_AGSF_transfer.py
Tests/Validation/Simulation/Force/test_Benchmark_AGSF_transfer_compare_Rag_var.py
Tests/Validation/Simulation/test_EEC_FEMM_IPMSM.py
Tests/Validation/Simulation/test_EEC_FEMM_SCIM.py
Tests/Validation/Simulation/test_EM_FEMM_IPMSM_varload.py
Tests/Validation/Simulation/test_EM_IPMSM_FL_001.py
Tests/Validation/Simulation/test_EM_SIPMSM_AL_001.py
Tests/Validation/Simulation/test_EM_SPMSM_FL_001.py
Tests/Validation/Simulation/test_EM_SPMSM_FL_002.py
Tests/Validation/Simulation/test_EM_SynRM_FL_001.py
pyleecan/Methods/Simulation/MagFEMM/solve_FEMM_parallel.py

Hello, 
this PR resolves some issues with parallel FEMM, i.e. almost all FEMM tests pass now (atleast with 'old' master 66ef525520b37b47fe3c4aaaa2e6b63afcf37ecf and except for 'test_FEMM_periodicity' that got some other issue).
Best regards, Sebastian

parallel Femm fix

---

Tests/Simulation/test_StructElmer.py
pyleecan/Classes/Class_Dict.json
pyleecan/Classes/ElmerResultsVTU.py
pyleecan/Classes/import_all.py
pyleecan/Functions/load_switch.py
pyleecan/Generator/ClassesRef/Elmer/ElmerResultsVTU.csv
pyleecan/Methods/Elmer/ElmerResultsVTU/__init__.py
pyleecan/Methods/Elmer/ElmerResultsVTU/build_meshsolution.py
pyleecan/Methods/Elmer/ElmerResultsVTU/get_meshsolution.py
pyleecan/Methods/Simulation/StructElmer/__init__.py
pyleecan/Methods/Simulation/StructElmer/get_meshsolution.py

This PR add a new Elmer class to load the vtu results into pyleecan. 
Since this class has only one method, it could have been done with a function also. But because there are also other convenient Elmer classes, I decided for a class over a function.

[NF] ElmerResultsVTU helper class to load results

---

pyleecan/GUI/Tools/GuiOption/WGuiOption.py

This PR allows to use the Options Widget without actual instances of DMachineSetup and MatLib.

[CO] WGuiOption

---

pyleecan/GUI/Tools/WPathSelector/WPathSelectorV.py

Fix bug where canceled selection dialog sets path to empty string.

[BC] WPathSelector

---

pyleecan/GUI/Dialog/DMatLib/DMatLib.py
pyleecan/GUI/Tools/WImport/WImportMatrixTable/Ui_WImportMatrixTable.py
pyleecan/GUI/Tools/WImport/WImportMatrixTable/WImportMatrixTable.py
pyleecan/GUI/Tools/WImport/WImportMatrixTable/WImportMatrixTable.ui
pyleecan/GUI/Tools/WTableData/DTableData.py

This PR fixes some errors if the BH curve matrix is None.

[BC] DMatLib

---

pyleecan/Methods/Slot/HoleM57/build_geometry.py

There are some label issues with HoleM57 that raised some FEMM model build issues. With this PR this should be fix. 
Nevertheless, I seems we need to discuss the line labels with respect to 'get_mesh_param' FEMM function.

[BC] fix HoleM57

---

Tests/Functions/test_save_load.py
Tests/Functions/test_save_load_array.py
pyleecan/Functions/Load/load_array.py
pyleecan/Functions/Save/save_array.py

This PR introduces load and save functions for multidimensional ndarrays as csv files, e.g. to export winding matrices.
In comarison to json the data are more readable and can be edited more easily with your favorit spread sheet software.

[NF] load/save np array

---

pyleecan/GUI/Dxf/DXF_Hole.py
pyleecan/GUI/Dxf/DXF_Hole.ui
pyleecan/GUI/Dxf/DXF_Slot.py
pyleecan/GUI/Dxf/DXF_Slot.ui
pyleecan/GUI/Dxf/Ui_DXF_Hole.py
pyleecan/GUI/Dxf/Ui_DXF_Slot.py
pyleecan/GUI/Tools/WImport/WImportExcel/Ui_WImportExcel.py
pyleecan/GUI/Tools/WImport/WImportExcel/WImportExcel.ui

Hello all,
This PR introduces the possibility to set an offset to the machine center when importing a hole or slot. The center is also displayed directly in the plot:
When importing a slot, the point index are now displayed in the "plot" to ease the winding definition:
Best regards,
Pierre

[NF] Shift machine center for hole/slot DXF import

---

pyleecan/Methods/Machine/WindingUD/import_from_csv.py

This PR enables to import winding definitons that are an integer fraction of the actual number of slots. So it is easier for users to define windings, since they only have to design the least common multiple of the winding.

[NF] import partial winding csv

---

Tests/Methods/Machine/test_comp_periodicity.py
pyleecan/Methods/Machine/LamHole/plot.py
pyleecan/Methods/Machine/LamSlotWind/plot.py
pyleecan/Methods/Machine/Winding/comp_periodicity.py

[NF] Adding arrow and winding layer on plot

---

Tests/Validation/Loss/test_FEMM_Loss.py

This CO will improve the winding loss calculation in case there are asymmetric currents. (This isn't needed for the test itself, but will help if someone adapt the code from this test.)

[CO] loss test winding losses

---

pyleecan/Generator/ClassGenerator/class_generator.py
pyleecan/Generator/ClassGenerator/properties_generator.py

Bug correction for SciDataTool

[BC] Adding soft_name to property generation

---

Tests/Functions/test_save_load.py
pyleecan/Classes/Class_Dict.json
pyleecan/Classes/HoleUD.py
pyleecan/Classes/SlotUD.py
pyleecan/Classes/SlotUD2.py
pyleecan/Functions/Save/save_json.py
pyleecan/Functions/save.py
pyleecan/GUI/Dialog/DMachineSetup/SWSlot/PWSlot10/PWSlot10.py
pyleecan/GUI/Dxf/DXF_Hole.py
pyleecan/GUI/Dxf/DXF_Slot.py
pyleecan/Generator/ClassGenerator/class_generator.py
pyleecan/Generator/ClassGenerator/properties_generator.py
pyleecan/Generator/ClassesRef/Slot/HoleUD.csv
pyleecan/Generator/ClassesRef/Slot/SlotUD.csv
pyleecan/Generator/ClassesRef/Slot/SlotUD2.csv
pyleecan/Methods/Mesh/MeshVTK/as_dict.py

Hello,
This PR continues the discussion around the save function for json. 
- It should now be possible again to save object with no name property
- SlotUD/HoleUD now have a name property and are split in save
- indentation is now 2
@SebGue do you see anything else to fix/improve ? (I won't have time to work on "M400_50A_000001" to "M400-50A_Rotor-0")
Best regards,
Pierre

[CO] Save json

---

Tests/Methods/Machine/test_comp_periodicity.py
pyleecan/Methods/Output/OutMag/store.py

[BC] Correct unit and name of Tem_slice and Phi_wind_slice in store

---

pyleecan/GUI/Dialog/DMachineSetup/SPreview/WMachineTable/WMachineTable.py

I haven't checked if the time is correct or if it even matter here.

[BC] get stator current in WMachineTable

---

Tests/Methods/Machine/test_notch.py
pyleecan/Functions/FEMM/create_FEMM_boundary_conditions.py
pyleecan/Methods/Machine/LamHole/plot.py
pyleecan/Methods/Machine/Lamination/get_bore_desc.py
pyleecan/Methods/Simulation/MagFEMM/comp_flux_airgap.py
pyleecan/Methods/Simulation/MagFEMM/solve_FEMM_parallel.py
pyleecan/Methods/Slot/SlotCirc/build_geometry.py
pyleecan/Methods/Slot/SlotCirc/check.py

Few corrections to implement notches in Lamination object, especially LamHole rotors.
Also solve bug when importing FEMM files with worker parallelization.

Notch corrections for Lamination object

---

pyleecan/Methods/Machine/LamHole/build_geometry.py

Add missing input parameter to LamHole.build_geometry to enable Notches.

[CC] Notches in LamHole

---

pyleecan/Functions/GMSH/draw_GMSH.py
pyleecan/Functions/GMSH/draw_surf_line.py
pyleecan/Functions/GMSH/get_sliding_band.py

Revert "Improvements on creation of geometry and meshing by GMSH"

---

Tests/GUI/Dialog/DMachineSetup/test_SSimu.py
Tests/Methods/Simulation/test_magelmer.py
Tests/Simulation/test_StructElmer.py
pyleecan/Functions/GMSH/comp_gmsh_mesh_dict.py
pyleecan/Functions/GMSH/draw_GMSH.py
pyleecan/Functions/GMSH/draw_surf_line.py
pyleecan/Functions/GMSH/get_air_box.py
pyleecan/Functions/GMSH/get_boundary_condition.py
pyleecan/Functions/GMSH/get_sliding_band.py
pyleecan/Methods/Simulation/MagElmer/get_meshsolution.py
pyleecan/Methods/Simulation/MagElmer/solve_FEA.py
pyleecan/__init__.py

Hello, 
This PR gather the modifications from @ajpina in #608  and #608 + some corrections on the tests (some not related to the GMSH modifications. I'm sorry that I didn't review these PR earlier, time is starting to be a very precious ressource on my side.
I will take the opportunity of closing this PR to release a new version of pyleecan with all the latest development in particular the work of @clementd08.
Best regards,
Pierre

Closing GMSH and Elmer PR
